import React from "react";
import Props from "../Props";

function MethanePyrolysis() {
  return (
    <Props
      heading="Pyrolysis of Methane into Green Hydrogen"
      para="AEP group team has developed this technology and designed the
  Plant module for secondary, continuous cycle, advanced pyrolysis of flue syn gas to pure hydrogen gas with a lot of carbon black & nano-carbon powder. 
  
  Thermo-chemical decomposition of waste without access of oxygen, without burning results in a flue gas mix of hydrocarbon gases like ethane, butane, butene, methane, propane, etc and water steam from natural waste moisture, precipitation, waste leachate or slurry. Water steam is necessary component for the thermo-chemical reactions between H2O and hydro-carbon molecules synthesis for a renewable gas mix creation. 
  
  After series of its filtration and cleansing from fly ash, hard carbon residue particles, destroying CO2/ CO gas by ionization and removing extra moisture, we get a flue gas mix with high content of methane used as resource for further technological manipulations. We segregate pure Methane, convert it to another gas and pass it through the secondary advanced pyrolysis module
  with liquid metal heated by aux industrial heat derived from the initial processing to increase energy efficiency to max available without using electrolysis. 
  
  Liquid metal coolant is often used on Navy submarines with nuclear reactors. Excessive heat from reactor 1st cooling circuit is collected by light liquid metal in fully enclosed cooling system to reduce risks and to transfer the heat to a 2nd enclosed cooling circuit using distilled fresh water to create dry steam for the sub propulsion turbines, then use 3rd cooling circuit with sea water. 
  
  In our plant, we employ the same principles to achieve maximum efficiency by harvesting the industrial heat from pyrolysis reactor to melt and to circulate a light metal for boosting the advanced pyrolysis conversion of syn gas passing through the liquid metal into hydrogen and carbon powder as a by-product. The hydrogen module requires a pilot testing after the proof-of-concept model. 
  
  Using this kind of secondary pyrolysis together with the advanced pyrolysis at the first stage of a waste processing allows us to cut both carbon and methane emissions completely with a maximum claim on entitlements for the carbon/methane credit certificates and maximum positive environmental impact. We eliminate even minuscular emissions generated by diesel/gas turbo generators of electricity generation module, when we use Hydrogen production module instead.
  "
    />
  );
}

export default MethanePyrolysis;
